version: '3'
services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    tty: true
    volumes:
      - .data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=rest-api
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "9000:80"
    depends_on:
      - db